package com.example.bt_thuctap.common;

import android.content.Context;
import android.content.SharedPreferences;

import com.example.bt_thuctap.model.DuLieuNhanVe;

public class Constant {
    public static final String TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJFUFMiLCJ1c2VyX2lkIjoiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkFkbWluaXN0cmF0b3IiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFkbWluIiwicHJpdmlsZWdlcyI6Ik1hbmFnZUN1c3RvbWVyLE1hbmFnZVByb21vdGlvbixNYW5hZ2VSZWdpc3RlcixNYW5hZ2VSb2xlLE1hbmFnZVNlcnZpY2UsTWFuYWdlVXNlcixWaWV3Q3VzdG9tZXIsVmlld1Byb21vdGlvbixWaWV3UmVnaXN0ZXIsVmlld1JvbGUsVmlld1NlcnZpY2UsVmlld1VzZXIiLCJ1bml0X2lkIjoiMSIsIm5iZiI6MTYyNTU1ODY5MiwiZXhwIjoxNjI1NTU5ODkyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L0VQUy5BUEkiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0L0VQUy5UU0MifQ.5SV57rvS6KOXvpBFpGVKMcw-eC7xjuMqk_wcmLK_YDM";

}
